language : cpp
env:
  - DISPLAY=:99.0
compiler:
  - gcc
before_install:
    - sudo add-apt-repository --yes ppa:beineri/opt-qt551
    - sudo add-apt-repository --yes "deb http://download.opensuse.org/repositories/home:/benlau/xUbuntu_15.10 ./"
    - sudo apt-get update -qq
    - apt-cache search qt5
    - sudo apt-get install --force-yes -qq qt55quickcontrols  qt55declarative qt55script qt55graphicaleffects qpm
    - sh -e /etc/init.d/xvfb start
    - openssl aes-256-cbc -K $encrypted_33bab58a9e7d_key -iv $encrypted_33bab58a9e7d_iv -in .travis/deploy_key.enc -out .travis/deploy_key -d
    - chmod 400 .travis/deploy_key

script:
    - source /opt/qt55/bin/qt55-env.sh
    - cd tests/quickcrossunittests
    - qpm install
    - qmake
    - make
    - ls
    - ./tst_quickcrossunittests
    - cd ../../
    - eval `ssh-agent -s`
    - ssh-add .travis/deploy_key
    - export QT_DOCS_STYLE=/opt/qt55/doc/global/html/style/offline.css
    - git remote remove origin
    - git remote add origin git@github.com:benlau/quickcross.git
    - git config --global user.email "xbenlau@gmail.com"
    - git config --global user.name "Ben Lau"
    - bash .travis/deploy_pages.sh

