language : cpp
env:
  - DISPLAY=:99.0
compiler:
  - gcc
before_install:
    - export PATH=$PWD/.travis:$PATH
    - sudo add-apt-repository --yes "deb http://download.opensuse.org/repositories/home:/benlau/xUbuntu_15.10 ./"
    - sudo apt-get update -qq
    - sudo apt-get install --force-yes -qq qpm
    - sh -e /etc/init.d/xvfb start
    - ./.travis/qt-5.5.1
    - openssl aes-256-cbc -K $encrypted_33bab58a9e7d_key -iv $encrypted_33bab58a9e7d_iv -in .travis/deploy_key.enc -out .travis/deploy_key -d
    - chmod 400 .travis/deploy_key

script:
    - set -e
    - source qt-5.5.1.env
    - export QT_DOCS_STYLE=$PWD/Qt/Docs/Qt-5.5/global/template/style/offline.css
    - cd tests/quickcrossunittests
    - qpm install
    - qmake
    - make
    - ls
    - ./tst_quickcrossunittests
    - cd ../../
    - eval `ssh-agent -s`
    - ssh-add .travis/deploy_key
    - git remote remove origin
    - git remote add origin git@github.com:benlau/quickcross.git
    - git config --global user.email "xbenlau@gmail.com"
    - git config --global user.name "Ben Lau"
    - bash .travis/deploy_pages.sh

